# -*- coding: utf-8 -*-
"""
유니버스 필터·요약에서 사용하는 ``reason_code`` 상수.

모든 제외/통과 코드는 이 모듈에서만 정의하고, 필터 엔진이 참조한다.
"""
from __future__ import annotations

REASON_PASS: str = "PASS"
REASON_INVALID_SYMBOL: str = "INVALID_SYMBOL"
REASON_EXCLUDED_EXCHANGE: str = "EXCLUDED_EXCHANGE"
REASON_INACTIVE: str = "INACTIVE"
REASON_SCREENER_ETF: str = "SCREENER_ETF"
REASON_SCREENER_FUND: str = "SCREENER_FUND"
REASON_ETF_LIST_MATCH: str = "ETF_LIST_MATCH"
REASON_STOCK_LIST_EXCLUDED_TYPE: str = "STOCK_LIST_EXCLUDED_TYPE"
REASON_EXCLUDED_INDUSTRY: str = "EXCLUDED_INDUSTRY"
REASON_EXCLUDED_NAME_PATTERN: str = "EXCLUDED_NAME_PATTERN"
REASON_EXCLUDED_SYMBOL_SUFFIX: str = "EXCLUDED_SYMBOL_SUFFIX"

ALL_REASON_CODES: tuple[str, ...] = (
    REASON_PASS,
    REASON_INVALID_SYMBOL,
    REASON_EXCLUDED_EXCHANGE,
    REASON_INACTIVE,
    REASON_SCREENER_ETF,
    REASON_SCREENER_FUND,
    REASON_ETF_LIST_MATCH,
    REASON_STOCK_LIST_EXCLUDED_TYPE,
    REASON_EXCLUDED_INDUSTRY,
    REASON_EXCLUDED_NAME_PATTERN,
    REASON_EXCLUDED_SYMBOL_SUFFIX,
)
